name: Prettier Check
on:
  pull_request:
    branches:
      - main # The branch the action should start when pushed to.
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Prevents overlap if there are multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '17.5.0'
          cache: npm

      - name: Install Node Modules
        run: npm i

      - name: Check Prettier
        run: npx prettier --check .
